# Базовый образ Python
FROM python:3.11-slim

# Установка рабочей директории внутри контейнера
WORKDIR /app

# Скопировать файл зависимостей
COPY requirements.txt .

# Установить зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Скопировать весь проект внутрь контейнера
COPY . .

# Открываем порт (если требуется, можно опустить)
EXPOSE 8000

# Команда запуска
CMD [ "python", "webhook_server.py"]